Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64"
	config.vm.provision :shell, inline: "echo A"

	config.vm.define :Server do |server|
		server.vm.hostname = "eflaquetS"
		server.vm.network :private_network, ip: "192.168.56.110"
		server.vm.provider :virtualbox do |vb|
			vb.memory = "1024"
			vb.cpus = 1
		end
		server.vm.provision :shell, path: "config/controller.sh"
	end

	config.vm.define :ServerWorker do |worker|
		worker.vm.hostname = "eflaquetSW" #a changer avec un autre login
		worker.vm.network :private_network, ip: "192.168.56.111"
		worker.vm.provider :virtualbox do |vb|
			vb.memory = "1024"
			vb.cpus = 1
		end
		worker.vm.provision :shell, path: "config/agent.sh"
	end
end
